### PR TITLE
#2 Style CountryDetails page using tailwind

### PR DESCRIPTION
**Pull request by Potato-29**
Hi there! I've designed the UI as per the issue, now all thats left is to feed it the data pulled from the API,
requesting to close issue #2 Thanks :)

### CODE REVIEW

**Review by cod-lvr — CHANGES_REQUESTED** [review]
Awesome work you did, I really appreciate your effort, but one concern is creating styles folder and use external CSS file is not an approach I use in this project that mix make it hard for other developer to read the project code, the styles should be inline in the component.

**Comment by Potato-29** [comment]
Ah my bad really sorry, I thought inline would look messy so I did external, I'll fix it up as soon as I recover from my fever :(

**Comment by Potato-29** [comment]
I've made the changes

**Comment by cod-lvr** [comment]
Clear as Crystal, well Done.

**Pull request merged**
